## screener

In [14]:
import requests
import pandas as pd

from bs4 import BeautifulSoup

In [7]:
# URL of the page to scrape
url = "https://www.screener.in/company/TATAMOTORS/consolidated/"

# Send a GET request to the webpage
response = requests.get(url)

In [8]:
response

In [9]:
# Parse the content with BeautifulSoup
soup = BeautifulSoup(response.content, 'html.parser')

In [12]:
# Find the Pros section
pros_section = soup.find('div', class_='pros')
pros_list = pros_section.find_all('li') if pros_section else []

print("Pros:")
for pro in pros_list:
    print(pro.text.strip())

# Find the Cons section
cons_section = soup.find('div', class_='cons')
cons_list = cons_section.find_all('li') if cons_section else []

print("\nCons:")
for con in cons_list:
    print(con.text.strip())

Pros:
Company has reduced debt.
Company has delivered good profit growth of 93.1% CAGR over last 5 years

Cons:
Stock is trading at 4.01 times its book value
Tax rate seems low

In [79]:
# Find the table under the 'quarters' section
quarters_section = soup.find('section', id='quarters')
table = quarters_section.find('table')

# Extract the header (quarters)
headers = [th.text.strip() for th in table.find_all('th')]

# Extract the data rows
rows = []
for tr in table.find_all('tr')[1:]:
    cells = [td.text.strip() or f"https://www.screener.in{td.find('a', href=True)['href']}" for td in tr.find_all('td')]

    rows.append(cells)

# Create a DataFrame
quarters_section_df = pd.DataFrame(rows, columns=headers)
quarters_section_df.head()

,,Jun 2021,Sep 2021,Dec 2021,Mar 2022,Jun 2022,Sep 2022,Dec 2022,Mar 2023,Jun 2023,Sep 2023,Dec 2023,Mar 2024,Jun 2024
0,Sales +,"66,406","61,379","72,229","78,439","71,935","79,611","88,489","105,932","102,236","105,128","110,577","119,986","108,048"
1,Expenses +,"61,164","57,262","65,151","70,156","69,522","74,039","77,668","92,818","89,019","91,361","95,159","102,851","92,263"
2,Operating Profit,"5,243","4,117","7,078","8,283","2,413","5,572","10,820","13,114","13,217","13,767","15,418","17,135","15,785"
3,OPM %,8%,7%,10%,11%,3%,7%,12%,12%,13%,13%,14%,14%,15%
4,Other Income +,584,862,789,189,"2,381","1,351","1,130","1,453",895,"1,507","1,604","1,619","1,747"

In [46]:
# Find the section with id="profit-loss"
profit_loss_section = soup.find('section', id='profit-loss')

# Extract the table within this section
table = profit_loss_section.find('table', class_='data-table')

# Extract headers
profit_loss_section_headers = [header.text.strip() for header in table.find_all('th')]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    cells = [cell.text.strip() for cell in row.find_all('td')]
    rows.append(cells)

# Create a DataFrame
profit_loss_section_df = pd.DataFrame(rows, columns=profit_loss_section_headers)
# profit_loss_section_df

In [49]:
# Find the section with id="profit-loss"
balance_sheet_section = soup.find('section', id='balance-sheet')

# Extract the table within this section
table = balance_sheet_section.find('table', class_='data-table')

# Extract headers
balance_sheet_headers = [header.text.strip() for header in table.find_all('th')]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    cells = [cell.text.strip() for cell in row.find_all('td')]
    rows.append(cells)

# Create a DataFrame
balance_sheet_df = pd.DataFrame(rows, columns=balance_sheet_headers)
# balance_sheet_df

In [52]:
# Find the section with id="profit-loss"
cash_flow_section = soup.find('section', id='cash-flow')

# Extract the table within this section
table = cash_flow_section.find('table', class_='data-table')

# Extract headers
cash_flow_section_headers = [header.text.strip() for header in table.find_all('th')]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    cells = [cell.text.strip() for cell in row.find_all('td')]
    rows.append(cells)

# Create a DataFrame
cash_flow_df = pd.DataFrame(rows, columns=cash_flow_section_headers)
cash_flow_df

,,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,Mar 2021,Mar 2022,Mar 2023,Mar 2024
0,Cash from Operating Activity +,"22,163","36,151","35,531","37,900","30,199","23,857","18,891","26,633","29,001","14,283","35,388","67,915"
1,Cash from Investing Activity +,"-22,969","-27,991","-36,232","-36,694","-39,571","-25,139","-20,878","-33,115","-25,672","-4,444","-15,417","-22,782"
2,Cash from Financing Activity +,"-1,692","-3,883","5,201","-3,795","6,205","2,012","8,830","3,390","9,904","-3,380","-26,243","-37,006"
3,Net Cash Flow,"-2,499","4,277","4,500","-2,589","-3,167",730,"6,843","-3,092","13,232","6,459","-6,272","8,128"

In [53]:


# Find the section with id="profit-loss"
ratios_section = soup.find('section', id='ratios')

# Extract the table within this section
table = ratios_section.find('table', class_='data-table')

# Extract headers
ratios_section_headers = [header.text.strip() for header in table.find_all('th')]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    cells = [cell.text.strip() for cell in row.find_all('td')]
    rows.append(cells)

# Create a DataFrame
ratios_df = pd.DataFrame(rows, columns=ratios_section_headers)
ratios_df

,,Mar 2013,Mar 2014,Mar 2015,Mar 2016,Mar 2017,Mar 2018,Mar 2019,Mar 2020,Mar 2021,Mar 2022,Mar 2023,Mar 2024
0,Debtor Days,21,17,17,18,19,25,23,16,19,16,17,14
1,Inventory Days,64,69,67,73,77,83,73,82,83,71,66,64
2,Days Payable,137,146,131,138,138,151,133,145,175,141,128,126
3,Cash Conversion Cycle,-51,-60,-47,-46,-41,-43,-38,-48,-74,-53,-45,-48
4,Working Capital Days,-57,-41,-44,-47,-50,-50,-53,-68,-48,-32,-24,-24
5,ROCE %,21%,22%,21%,15%,9%,9%,2%,-0%,6%,1%,6%,20%

shareholding

In [54]:
# Find the section with id="profit-loss"
shareholding_section = soup.find('section', id='shareholding')

# Extract the table within this section
table = shareholding_section.find('table', class_='data-table')

# Extract headers
shareholding_section_headers = [header.text.strip() for header in table.find_all('th')]

# Extract rows
rows = []
for row in table.find_all('tr')[1:]:  # Skip the header row
    cells = [cell.text.strip() for cell in row.find_all('td')]
    rows.append(cells)

# Create a DataFrame
shareholding_df = pd.DataFrame(rows, columns=shareholding_section_headers)
shareholding_df

,,Sep 2021,Dec 2021,Mar 2022,Jun 2022,Sep 2022,Dec 2022,Mar 2023,Jun 2023,Sep 2023,Dec 2023,Mar 2024,Jun 2024
0,Promoters +,46.41%,46.40%,46.40%,46.40%,46.40%,46.39%,46.39%,46.39%,46.38%,46.37%,46.36%,46.36%
1,FIIs +,13.35%,14.57%,14.45%,13.71%,14.13%,13.89%,15.34%,17.72%,18.40%,18.62%,19.20%,18.18%
2,DIIs +,13.30%,13.64%,14.38%,15.17%,14.75%,15.21%,17.69%,17.38%,17.37%,17.25%,16.01%,15.93%
3,Government +,0.15%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%,0.14%
4,Public +,26.80%,25.24%,24.62%,24.57%,24.58%,24.36%,20.41%,18.38%,17.70%,17.60%,18.31%,19.39%
5,No. of Shareholders,"26,95,590","32,52,513","37,97,100","40,08,506","39,76,830","39,93,043","38,14,831","35,02,408","37,73,314","41,84,369","46,16,908","50,98,550"

In [59]:

# Find the 'documents' section
documents_section = soup.find('section', id='documents')

# Find all links within the 'documents' section
links = documents_section.find_all('a')

# Extract href and text from each link
link_data = []
for link in links:
    href = link.get('href')
    text = link.text.strip()
    link_data.append([text,href])

# Create a pandas DataFrame
df = pd.DataFrame(link_data, columns=['Text','Link'])

In [65]:
df

,Text,Link
0,All,https://www.bseindia.com/stock-share-price/tat...
1,Announcement under Regulation 30 (LODR)-Earnin...,https://www.bseindia.com/stockinfo/AnnPdfOpen....
2,Compliances-Reg. 39 (3) - Details of Loss of C...,https://www.bseindia.com/stockinfo/AnnPdfOpen....
3,Compliances-Reg. 39 (3) - Details of Loss of C...,https://www.bseindia.com/stockinfo/AnnPdfOpen....
4,Announcement under Regulation 30 (LODR)-Scheme...,https://www.bseindia.com/stockinfo/AnnPdfOpen....
...,...,...
67,PPT,https://www.bseindia.com/stockinfo/AnnPdfOpen....
68,Transcript,https://www.tatamotors.com/wp-content/uploads/...
69,Transcript,https://www.tatamotors.com/wp-content/uploads/...
70,Transcript,https://www.tatamotors.com/wp-content/uploads/...
71,Transcript,https://aicl-mum-bucket.s3.ap-south-1.amazonaw...

In [67]:

# Find the div with class "documents flex-column"
documents_div = soup.find('div', class_='documents flex-column')

data = []

if documents_div:
    # Extract the header
    header = documents_div.find('h3').text.strip()
    print(f"Header: {header}")

    # Find all links within the div
    links = documents_div.find_all('a')

    for link in links:
        href = link.get('href')
        text = link.text.strip()
        
        # Extract the smaller text if it exists
        smaller_div = link.find('div', class_='ink-600 smaller')
        smaller_text = smaller_div.text.strip() if smaller_div else ''
        
        # Add data to the list
        data.append({
            'text': text,
            'url': href,
            'details': smaller_text
        })

    # Create DataFrame
    df = pd.DataFrame(data)
    
    print("\nDataFrame contents:")
    print(df)
    
    # Optionally, save to CSV
    df.to_csv('announcements_data.csv', index=False)
    print("\nData saved to 'announcements_data.csv'")
else:
    print("The specified div was not found.")

Header: Announcements

DataFrame contents:
                                                text  \
0                                                All
1  Announcement under Regulation 30 (LODR)-Earnin...
2  Compliances-Reg. 39 (3) - Details of Loss of C...
3  Compliances-Reg. 39 (3) - Details of Loss of C...
4  Announcement under Regulation 30 (LODR)-Scheme...
5  Compliances-Reg. 39 (3) - Details of Loss of C...

                                                 url  \
0  https://www.bseindia.com/stock-share-price/tat...
1  https://www.bseindia.com/stockinfo/AnnPdfOpen....
2  https://www.bseindia.com/stockinfo/AnnPdfOpen....
3  https://www.bseindia.com/stockinfo/AnnPdfOpen....
4  https://www.bseindia.com/stockinfo/AnnPdfOpen....
5  https://www.bseindia.com/stockinfo/AnnPdfOpen....

                                             details
0
1  13m - Reg 30 of the SEBI (LODR) Regulations, 2...
2
3
4  1d - Copy of the Order obtained from Hon''ble ...
5

Data saved to 'announcements_data.csv'

In [69]:
df

,text,url,details
0,All,https://www.bseindia.com/stock-share-price/tat...,
1,Announcement under Regulation 30 (LODR)-Earnin...,https://www.bseindia.com/stockinfo/AnnPdfOpen....,"13m - Reg 30 of the SEBI (LODR) Regulations, 2..."
2,Compliances-Reg. 39 (3) - Details of Loss of C...,https://www.bseindia.com/stockinfo/AnnPdfOpen....,
3,Compliances-Reg. 39 (3) - Details of Loss of C...,https://www.bseindia.com/stockinfo/AnnPdfOpen....,
4,Announcement under Regulation 30 (LODR)-Scheme...,https://www.bseindia.com/stockinfo/AnnPdfOpen....,1d - Copy of the Order obtained from Hon''ble ...
5,Compliances-Reg. 39 (3) - Details of Loss of C...,https://www.bseindia.com/stockinfo/AnnPdfOpen....,

In [71]:

# Find the div with class "documents annual-reports flex-column"
annual_reports_div = soup.find('div', class_='documents annual-reports flex-column')

data = []

if annual_reports_div:
    # Find all links within the div
    links = annual_reports_div.find_all('a')

    for link in links:
        href = link.get('href')
        text = link.text.strip()
        
        # Extract the smaller text if it exists
        smaller_div = link.find('div', class_='ink-600 smaller')
        smaller_text = smaller_div.text.strip() if smaller_div else ''
        
        # Add data to the list
        data.append({
            'Financial Year': text,
            'URL': href,
            'Source': smaller_text
        })

    # Create DataFrame
    df = pd.DataFrame(data)
    
    print("DataFrame contents:")
    # print(df)
    
    # Optionally, save to CSV
    df.to_csv('annual_reports_data.csv', index=False)
    print("\nData saved to 'annual_reports_data.csv'")
else:
    print("The specified div was not found.")

DataFrame contents:

Data saved to 'annual_reports_data.csv'

In [75]:

# Find the div with class "documents credit-ratings flex-column"
credit_ratings_div = soup.find('div', class_='documents credit-ratings flex-column')

data = []

if credit_ratings_div:
    # Find all links within the div
    links = credit_ratings_div.find_all('a')

    for link in links:
        href = link.get('href')
        text = link.find(text=True, recursive=False).strip()
        
        # Extract the smaller text
        smaller_div = link.find('div', class_='ink-600 smaller')
        smaller_text = smaller_div.text.strip() if smaller_div else ''
        
        # Split the smaller text into date and source
        date, source = smaller_text.split(' from ')
        
        # Add data to the list
        data.append({
            'Update Type': text,
            'Date': date.strip(),
            'Source': source.strip(),
            'URL': href
        })

    # Create DataFrame
    df = pd.DataFrame(data)
    
    print("DataFrame contents:")
    # print(df)
    
    # Optionally, save to CSV
    df.to_csv('credit_ratings_data.csv', index=False)
    print("\nData saved to 'credit_ratings_data.csv'")
else:
    print("The specified div was not found.")

DataFrame contents:

Data saved to 'credit_ratings_data.csv'

c:\Users\bhaut\anaconda3\envs\tf\lib\site-packages\ipykernel_launcher.py:12: DeprecationWarning: The 'text' argument to find()-type methods is deprecated. Use 'string' instead.
  if sys.path[0] == "":

In [76]:
df

,Update Type,Date,Source,URL
0,Rating update,5 Jul,care,https://www.careratings.com/upload/CompanyFile...
1,Rating update,13 Jun,icra,https://www.icra.in/Rationale/ShowRationaleRep...
2,Rating update,13 Jun,crisil,https://www.crisil.com/mnt/winshare/Ratings/Ra...
3,Rating update,2 Apr,care,https://www.careratings.com/upload/CompanyFile...
4,Rating update,13 Mar,icra,https://www.icra.in/Rationale/ShowRationaleRep...
5,Rating update,13 Mar,care,https://www.careratings.com/upload/CompanyFile...

In [77]:

# Find the div with class "documents concalls flex-column"
concalls_div = soup.find('div', class_='documents concalls flex-column')

data = []

if concalls_div:
    # Find all list items within the div
    items = concalls_div.find_all('li', class_='flex flex-gap-8 flex-wrap')

    for item in items:
        # Extract date
        date = item.find('div', class_='ink-600 font-size-15 font-weight-500 nowrap').text.strip()

        # Initialize variables
        transcript = notes = ppt = "N/A"

        # Extract links
        links = item.find_all('a', class_='concall-link')
        for link in links:
            if 'Transcript' in link.text:
                transcript = link['href']
            elif 'PPT' in link.text:
                ppt = link['href']

        # Extract notes (which is a button, not a link)
        notes_button = item.find('button', class_='concall-link', string='Notes')
        if notes_button:
            notes = notes_button['data-url']

        # Add data to the list
        data.append({
            'Date': date,
            'Transcript': transcript,
            'Notes': notes,
            'PPT': ppt
        })

    # Create DataFrame
    df = pd.DataFrame(data)
    
    print("DataFrame contents:")
    # print(df)
    
    # Optionally, save to CSV
    df.to_csv('concalls_data.csv', index=False)
    print("\nData saved to 'concalls_data.csv'")
else:
    print("The specified div was not found.")

DataFrame contents:

Data saved to 'concalls_data.csv'

In [78]:
df

,Date,Transcript,Notes,PPT
0,Jun 2024,N/A,N/A,https://www.tatamotors.com/wp-content/uploads/...
1,May 2024,https://www.bseindia.com/xml-data/corpfiling/A...,N/A,https://www.tatamotors.com/wp-content/uploads/...
2,Mar 2024,N/A,N/A,https://aicl-mum-bucket.s3.ap-south-1.amazonaw...
3,Feb 2024,https://www.bseindia.com/xml-data/corpfiling/A...,N/A,https://aicl-mum-bucket.s3.ap-south-1.amazonaw...
4,Feb 2024,N/A,N/A,https://www.tatamotors.com/wp-content/uploads/...
5,Dec 2023,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
6,Sep 2023,N/A,N/A,https://www.tatamotors.com/wp-content/uploads/...
7,Jul 2023,https://www.tatamotors.com/wp-content/uploads/...,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
8,Jul 2023,https://aicl-mum-bucket.s3.ap-south-1.amazonaw...,N/A,https://www.tatamotors.com/wp-content/uploads/...
9,Jun 2023,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
10,May 2023,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
11,Feb 2023,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
12,Dec 2022,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
13,Nov 2022,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
14,Nov 2022,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
15,Aug 2022,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
16,May 2022,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
17,May 2022,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
18,Feb 2022,https://www.bseindia.com/stockinfo/AnnPdfOpen....,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
19,Jan 2022,https://www.tatamotors.com/wp-content/uploads/...,N/A,N/A
20,Nov 2021,https://www.tatamotors.com/wp-content/uploads/...,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
21,Nov 2021,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
22,Oct 2021,https://www.tatamotors.com/wp-content/uploads/...,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
23,Jul 2021,https://www.tatamotors.com/wp-content/uploads/...,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
24,May 2021,https://www.tatamotors.com/wp-content/uploads/...,N/A,N/A
25,Feb 2021,N/A,N/A,https://www.bseindia.com/stockinfo/AnnPdfOpen....
26,Jan 2021,https://www.tatamotors.com/wp-content/uploads/...,N/A,N/A
27,Oct 2020,https://www.tatamotors.com/wp-content/uploads/...,N/A,N/A
28,Jul 2020,https://www.tatamotors.com/wp-content/uploads/...,N/A,N/A
29,Jan 2017,https://aicl-mum-bucket.s3.ap-south-1.amazonaw...,N/A,N/A